"""add_media_fields_to_broadcasts

Revision ID: 05766da697b6
Revises: 795df379fce9
Create Date: 2025-12-29 08:21:10.521793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05766da697b6'
down_revision: Union[str, None] = '795df379fce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhooks_bot_id', table_name='webhooks')
    op.drop_index('ix_webhooks_id', table_name='webhooks')
    op.drop_index('ix_webhooks_owner_id', table_name='webhooks')
    op.drop_table('webhooks')
    op.add_column('broadcasts', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('broadcasts', sa.Column('media_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'media_url')
    op.drop_column('broadcasts', 'media_type')
    op.create_table('webhooks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='webhooks_bot_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='webhooks_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='webhooks_pkey')
    )
    op.create_index('ix_webhooks_owner_id', 'webhooks', ['owner_id'], unique=False)
    op.create_index('ix_webhooks_id', 'webhooks', ['id'], unique=False)
    op.create_index('ix_webhooks_bot_id', 'webhooks', ['bot_id'], unique=False)
    # ### end Alembic commands ###

