"""add_media_files_to_broadcasts

Revision ID: 77ba87bd2d50
Revises: b23f41fa96dd
Create Date: 2025-12-29 19:33:01.352420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ba87bd2d50'
down_revision: Union[str, None] = 'b23f41fa96dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('media_files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'media_files')
    # ### end Alembic commands ###

