"""add_message_templates_user_tags_triggers_webhooks

Revision ID: 795df379fce9
Revises: bd65c601f03a
Create Date: 2025-12-27 09:57:31.495325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795df379fce9'
down_revision: Union[str, None] = 'bd65c601f03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_bot_id'), 'message_templates', ['bot_id'], unique=False)
    op.create_index(op.f('ix_message_templates_id'), 'message_templates', ['id'], unique=False)
    op.create_table('triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_bot_id'), 'triggers', ['bot_id'], unique=False)
    op.create_index(op.f('ix_triggers_id'), 'triggers', ['id'], unique=False)
    op.create_table('user_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tags_bot_id'), 'user_tags', ['bot_id'], unique=False)
    op.create_index(op.f('ix_user_tags_id'), 'user_tags', ['id'], unique=False)
    op.create_index(op.f('ix_user_tags_name'), 'user_tags', ['name'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_bot_id'), 'webhooks', ['bot_id'], unique=False)
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_webhooks_owner_id'), 'webhooks', ['owner_id'], unique=False)
    op.create_table('user_tags_association',
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['user_tags.id'], ),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('telegram_user_id', 'tag_id')
    )
    op.alter_column('bots', 'continue_button_text',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'✅ Продолжить'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'continue_button_text',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'✅ Продолжить'::character varying"))
    op.drop_table('user_tags_association')
    op.drop_index(op.f('ix_webhooks_owner_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_bot_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_user_tags_name'), table_name='user_tags')
    op.drop_index(op.f('ix_user_tags_id'), table_name='user_tags')
    op.drop_index(op.f('ix_user_tags_bot_id'), table_name='user_tags')
    op.drop_table('user_tags')
    op.drop_index(op.f('ix_triggers_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_bot_id'), table_name='triggers')
    op.drop_table('triggers')
    op.drop_index(op.f('ix_message_templates_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_bot_id'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###

