"""add_template_id_to_broadcasts

Revision ID: b23f41fa96dd
Revises: dd4dc8a566a9
Create Date: 2025-12-29 18:51:05.699174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23f41fa96dd'
down_revision: Union[str, None] = 'dd4dc8a566a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_broadcasts_template_id'), 'broadcasts', ['template_id'], unique=False)
    op.create_foreign_key(None, 'broadcasts', 'message_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'broadcasts', type_='foreignkey')
    op.drop_index(op.f('ix_broadcasts_template_id'), table_name='broadcasts')
    op.drop_column('broadcasts', 'template_id')
    # ### end Alembic commands ###

