"""add_continue_button_text

Revision ID: bd65c601f03a
Revises: ff9c01feaeb1
Create Date: 2025-12-27 08:56:01.507466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd65c601f03a'
down_revision: Union[str, None] = 'ff9c01feaeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('continue_button_text', sa.String(), nullable=True))
    # Устанавливаем значение по умолчанию для существующих записей
    op.execute("UPDATE bots SET continue_button_text = '✅ Продолжить' WHERE continue_button_text IS NULL")
    # Теперь делаем поле NOT NULL с дефолтным значением
    op.alter_column('bots', 'continue_button_text', nullable=False, server_default="✅ Продолжить")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'continue_button_text')
    # ### end Alembic commands ###

