"""add_filters_to_broadcasts

Revision ID: dd4dc8a566a9
Revises: 05766da697b6
Create Date: 2025-12-29 15:17:02.949470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4dc8a566a9'
down_revision: Union[str, None] = '05766da697b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('filters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'filters')
    # ### end Alembic commands ###

