"""add_actions_field_to_triggers

Revision ID: e8c27781d193
Revises: 77ba87bd2d50
Create Date: 2026-01-09 23:43:02.078262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c27781d193'
down_revision: Union[str, None] = '77ba87bd2d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triggers', sa.Column('actions', sa.JSON(), nullable=True))
    op.alter_column('triggers', 'action_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('triggers', 'action_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('triggers', 'actions')
    # ### end Alembic commands ###

