"""add_channels_to_bots

Revision ID: ff9c01feaeb1
Revises: 17077eebbd93
Create Date: 2025-12-26 21:11:18.590097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9c01feaeb1'
down_revision: Union[str, None] = '17077eebbd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('channels', sa.JSON(), nullable=True, server_default='[]'))
    # Обновляем существующие записи, устанавливая пустой массив
    op.execute("UPDATE bots SET channels = '[]' WHERE channels IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'channels')
    # ### end Alembic commands ###

